### ISSUE TITLE
Brake issue enable on the Gem upon pacmod v2 enable

### ISSUE THREAD

**Issue by hugomatic** [astuff/ros_pacmod#1]
if you send "true" to /pacmod/as_rx/enable without sending 0 to /pacmod/as_rx/accel_cmd and 0 /pacmod /as_rx/brake_cmd, you risk having the brake servo overheat (and blow the fuse)

This bug doesn't hapen with the joystick controller, because it sends all these messages. But the accel and brake should be set internally to a safe value when pacmod is enabled to allow enabling in a single message.

**Comment by JWhitleyWork** [comment]
@hugomatic - Thanks for bringing this issue to our attention. We will make sure that it gets fixed. We will likely fix this issue in the PACMod firmware to make sure you don't have to be running the ROS driver to fix this safety-critical issue. I'll post an update to this issue once the new firmware has been tested and released with this fix (current firmware release is 1.7.0 - 2.0.0 is currently in testing).

**Comment by JWhitleyWork** [comment]
@hugomatic - Please contact us if you haven't been notified of new firmware. There is newer firmware available (2.1.1) for your board. Thanks.
